# Generated by Django 4.2.5 on 2023-09-28 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='age',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=7),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='first_name',
            field=models.CharField(default='n/a', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(default='n/a', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='last_name',
            field=models.CharField(default='n/a', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='major',
            field=models.CharField(default='n/a', max_length=50),
            preserve_default=False,
        ),
    ]
